version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_weather
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: weather_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - weather_network

volumes:
  postgres_data:

networks:
  weather_network:
    driver: bridge